// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCm1Qr6wdG8VNGDuYMI2Ec7fhXRr6E-ds',
    appId: '1:20961022270:web:198378e3eed7db8a85dc6f',
    messagingSenderId: '20961022270',
    projectId: 'wallpaper-500c5',
    authDomain: 'wallpaper-500c5.firebaseapp.com',
    storageBucket: 'wallpaper-500c5.firebasestorage.app',
    measurementId: 'G-DBN3XQE0WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj9s2g3lFVPR4xaJcuHg2JESPyNfvmBc',
    appId: '1:20961022270:android:f3fe6b4d7898682f85dc6f',
    messagingSenderId: '20961022270',
    projectId: 'wallpaper-500c5',
    storageBucket: 'wallpaper-500c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRHqz0PtjiZTbuOS3AF0NxxlEiEAm5rs',
    appId: '1:20961022270:ios:605034b7f45abb3885dc6f',
    messagingSenderId: '20961022270',
    projectId: 'wallpaper-500c5',
    storageBucket: 'wallpaper-500c5.firebasestorage.app',
    iosBundleId: 'com.example.owallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRHqz0PtjiZTbuOS3AF0NxxlEiEAm5rs',
    appId: '1:20961022270:ios:605034b7f45abb3885dc6f',
    messagingSenderId: '20961022270',
    projectId: 'wallpaper-500c5',
    storageBucket: 'wallpaper-500c5.firebasestorage.app',
    iosBundleId: 'com.example.owallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_oRqK0S6q9ggZ9GgTxUFOqG3CsMJYSUk',
    appId: '1:20961022270:web:f1ffbe671ddbf34c85dc6f',
    messagingSenderId: '20961022270',
    projectId: 'wallpaper-500c5',
    authDomain: 'wallpaper-500c5.firebaseapp.com',
    storageBucket: 'wallpaper-500c5.firebasestorage.app',
    measurementId: 'G-HN3DQ5961G',
  );

}